export const LOAD_DOCUMENTS_SUCCESS = 'LOAD_DOCUMENTS_SUCCESS';
export const CREATE_DOCUMENT_SUCCESS = 'CREATE_DOCUMENT_SUCCESS';
export const CREATE_USER_SUCCESS = 'CREATE_USER_SUCCESS';

export const SET_LOGIN_PENDING = 'SET_LOGIN_PENDING';
export const SET_LOGIN_SUCCESS = 'SET_LOGIN_SUCCESS';
export const SET_LOGIN_ERROR = 'SET_LOGIN_ERROR';

export const LOG_OUT = 'LOG_OUT';

export const GET_USER_DOCUMENTS = 'GET_USER_DOCUMENTS';
export const UPDATE_DOCUMENT_SUCCESS = 'UPDATE_DOCUMENT_SUCCESS';

export const LOAD_USERS_SUCCESS = 'LOAD_USERS_SUCCESS';
export const LOAD_USER_SUCCESS = 'LOAD_USER_SUCCESS';

export const GET_A_DOCUMENT_SUCCESS = 'GET_A_DOCUMENT_SUCCESS';
export const DELETE_USER_SUCCESS = 'DELETE_USER_SUCCESS';

export const GET_A_DOCUMENT_FAILURE = 'GET_A_DOCUMENT_FAILURE';
export const GET_A_USER_FAILURE = 'GET_A_USER_FAILURE';

export const LOAD_PAGEDOCUMENTS_SUCCESS = 'LOAD_PAGEDOCUMENTS_SUCCESS';

export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS';
export const LOAD_PAGEUSERS_SUCCESS = 'LOAD_PAGEUSERS_SUCCESS';

export const SET_DELETE_SUCCESS = 'SET_DELETE_SUCCESS';
export const SET_DELETE_ERROR = 'SET_DELETE_ERROR';
export const DELETE_DOCUMENT_SUCCESS = 'DELETE_DOCUMENT_SUCCESS';

export const CREATE_ROLE_SUCCESS = 'CREATE_ROLE_SUCCESS';
export const LOAD_ROLES_SUCCESS = 'LOAD_ROLES_SUCCESS';
export const GET_ROLE_DOCUMENTS = 'GET_ROLE_DOCUMENTS';

export const AJAX_CALL_ERROR = 'AJAX_CALL_ERROR';

export const DELETE_ROLE_SUCCESS = 'DELETE_ROLE_SUCCESS';
